edit_uri: edit/main/docs/
copyright: '© marimo 2026'
watch:
  - docs/
  - marimo/
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/botterYosuke/marimo
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/5mR3Gmff
    - icon: material/email-newsletter
      link: https://marimo.io/newsletter
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@marimo_io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/marimo_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/marimo-io
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/marimo/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@botterYosuke
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - _static/js/analytics.js
  - _static/js/math.js
  - _static/js/init_kapa_widget.js
markdown_extensions:
  - blocks:MarimoBlocksExtension
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists # lists separated by paragraphs
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.blocks.details
  - pymdownx.emoji: null
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mkdocs-click
nav:
  - Home: index.md
  - Gameplay Guide: game-guide.md
  - Lore & Story: story.md
  - Security: security.md
  - FAQ: faq.md
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: '#FFFFFF'
        color: '#000000'
        font_family: Roboto
  - tags
  - redirects:
      redirect_maps: {}
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          load_external_modules: true
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
          options:
            preload_modules:
              - starlette
            filters:
              - '!^_'
            # General
            allow_inspection: false
            show_bases: true
            show_source: false
            find_stubs_package: true
            # Headings
            heading_level: 2
            show_root_heading: true
            # Members
            inherited_members: true
            # Docstrings
            merge_init_into_class: true
            show_if_no_docstring: true
            docstring_section_style: spacy
            docstring_style: google
            # Signatures
            separate_signature: true
            unwrap_annotated: true
            annotations_path: brief
            line_length: 60
            modernize_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
  - autorefs
hooks:
  - docs/hooks.py
repo_name: marimo-team/marimo
repo_url: https://github.com/botterYosuke/marimo
site_description: The next generation of Python notebooks
site_name: marimo
site_url: https://backcast-tan.vercel.app
theme:
  favicon: _static/favicon-32x32.png
  features:
    - announce.dismiss # dismissible announcements
    - content.code.copy # add copy button to code blocks
    - header.autohide # auto-hide header on scroll
    - navigation.indexes # section index pages
    - navigation.instant # faster page loads
    - navigation.path # show navigation breadcrumb path
    - navigation.tabs # show navigation as tabs
    - navigation.tabs.sticky # keep navigation tabs visible when scrolling
    - navigation.top # back to top button
    - navigation.tracking # updates URL as you scroll
    - navigation.footer # links to previous/next page, helpful for small screens
    - search.highlight # highlight search results
    - search.share # shareable search links
    - search.suggest # search suggestions
    - toc.follow # auto-scroll TOC
  font:
    code: Fira Mono
    text: PT Sans
  logo: _static/marimo-logotype-horizontal.png
  name: material
  palette:
    # Palette toggle for system preference and use brightness-auto icon
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

exclude_docs: |
  apps/README.md
