/* Copyright 2026 Marimo. All rights reserved. */

/**
 * スキル完了時にノートブックに注入するセルのテンプレート
 *
 * 注入パターン:
 * - パターンA: 新しいセルを追加（ヒントやヘルパー）
 * - パターンB: setup節を更新（モード変更）
 * - パターンC: 既存セルを更新（機能追加）
 */

export interface CellTemplate {
  name: string;
  code: string;
  config?: string; // e.g., "hide_code=True"
  afterCell?: string; // 挿入位置（このセルの後に挿入）
}

export interface InjectionTemplate {
  skillId: string;
  cells?: CellTemplate[];
  setupUpdate?: string; // setup節の更新内容
  description: string;
}

/**
 * スキル別の注入テンプレート
 * すべてのスキルが注入を必要とするわけではない
 */
export const injectionTemplates: InjectionTemplate[] = [
  // ========================================
  // サンドボックススキル
  // ========================================
  {
    skillId: "SANDBOX_002",
    description: "初めての購入後、保有株確認のヒントを追加",
    cells: [
      {
        name: "_hint_check_trades",
        code: [
          '"""',
          "保有株を確認してみましょう！",
          "",
          "bt.trades で保有中の取引一覧を取得できます。",
          "",
          "for trade in bt.trades:",
          '    print(f"銘柄: {trade.code}")',
          '    print(f"買値: {trade.entry_price:,.0f}円")',
          '"""',
          "mo.md('''",
          "## 次のステップ: 保有株を確認する",
          "",
          "株を買ったら、いくらで買えたか確認しましょう。",
          "",
          "```python",
          "for trade in bt.trades:",
          '    print(f"買値: {trade.entry_price:,.0f}円")',
          "```",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "SANDBOX_004",
    description: "初めての売却後、チャート確認のヒントを追加",
    cells: [
      {
        name: "_hint_review_chart",
        code: [
          '"""',
          "チャートで売買を振り返ってみましょう！",
          '"""',
          "mo.md('''",
          "## チャートで振り返る",
          "",
          "売買マーカーがチャートに表示されています。",
          "",
          "- **▲** 買いポイント",
          "- **▼** 売りポイント",
          "",
          "自分の判断を視覚的に確認できます。",
          "''')",
        ].join("\n"),
        afterCell: "_hint_check_trades",
      },
    ],
  },
  {
    skillId: "SANDBOX_006",
    description: "サンドボックス卒業時、ブリッジモードへの案内を追加",
    cells: [
      {
        name: "_bridge_intro",
        code: [
          '"""',
          "おめでとうございます！サンドボックスを卒業しました。",
          "次はブリッジモードで、裏側の仕組みを学びましょう。",
          '"""',
          "mo.md('''",
          "## サンドボックス卒業！",
          "",
          "おめでとうございます！基本操作をマスターしました。",
          "",
          "### 次のステージ: ブリッジモード",
          "",
          "サンドボックスでは、裏で自動的にデータが準備されていました。",
          "ブリッジモードでは、その「魔法」の正体を明かします。",
          "",
          "**次のステップ:** `bt.reveal_data()` を実行して、データの正体を確認しよう！",
          "",
          "**解禁される機能:**",
          "- データ取得の仕組みを学ぶ",
          "- 別の銘柄を追加する",
          "- 自分でセットアップする",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },

  // ========================================
  // ブリッジスキル
  // ========================================
  {
    skillId: "BRIDGE_001",
    description: "データの正体を確認した後、setup節の解説を追加",
    cells: [
      {
        name: "_reveal_setup_code",
        code: [
          '"""',
          "サンドボックスの裏側で動いていたコード",
          '"""',
          "mo.md('''",
          "## サンドボックスの裏側",
          "",
          "実は、あなたが `bt.buy()` を使えていたのは、",
          "裏でこのコードが動いていたからです：",
          "",
          "```python",
          "from BackcastPro import Backtest, get_stock_daily",
          "",
          "# データ取得",
          'df = get_stock_daily("7203")  # トヨタ',
          "",
          "# Backtest初期化",
          "bt = Backtest(cash=100_000, commission=0.001)",
          'bt.set_data({"7203": df})',
          "bt.start()",
          "```",
          "",
          "これがないと `buy()` は使えません！",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "BRIDGE_002",
    description: "自分でデータを取得した後、ソニーデータ追加のヒント",
    cells: [
      {
        name: "_hint_sony_data",
        code: [
          '"""',
          "ソニー(6758)のデータを取得してみましょう！",
          '"""',
          "# サンプル: ソニーのデータを取得",
          'sony_code = "6758"',
          "df_sony = get_stock_daily(sony_code)",
          "mo.md(f'''",
          "## ソニー(6758)のデータを取得しました！",
          "",
          "```python",
          'df_sony = get_stock_daily("6758")',
          "```",
          "",
          "データ期間: {df_sony.index[0].strftime('%Y-%m-%d')} 〜 {df_sony.index[-1].strftime('%Y-%m-%d')}",
          "データ行数: {len(df_sony)}行",
          "''')",
        ].join("\n"),
        afterCell: "_reveal_setup_code",
      },
    ],
  },
  {
    skillId: "BRIDGE_003",
    description: "フルモード解放時、セットアップ手順のテンプレートを追加",
    cells: [
      {
        name: "_full_mode_template",
        code: [
          '"""',
          "フルモード: 0からセットアップするテンプレート",
          "",
          "このセルのコードを参考に、自分でBacktestを初期化してみましょう！",
          '"""',
          "mo.md('''",
          "## フルモード解禁！",
          "",
          "これからは自分で0からセットアップします。",
          "",
          "### セットアップ手順",
          "",
          "```python",
          "# 1. インポート（setup節に既にあります）",
          "from BackcastPro import Backtest, get_stock_daily",
          "",
          "# 2. Backtest初期化",
          "bt = Backtest(cash=1_000_000, commission=0.001)",
          "",
          "# 3. 株価データ取得",
          'code = "7203"',
          "df = get_stock_daily(code)",
          "",
          "# 4. データをセット",
          "bt.set_data({code: df})",
          "",
          "# 5. これで準備完了！",
          "bt.buy()  # 買える！",
          "```",
          "",
          "下のセルで実際にやってみましょう。",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },

  // ========================================
  // フルモードスキル（主要なもののみ）
  // ========================================
  {
    skillId: "IND_001",
    description: "移動平均線を計算した後、SMAの使い方ヒント",
    cells: [
      {
        name: "_hint_sma_usage",
        code: [
          '"""',
          "移動平均線(SMA)の活用法",
          '"""',
          "mo.md('''",
          "## 移動平均線(SMA)を使った戦略",
          "",
          "### ゴールデンクロス戦略",
          "",
          "短期SMAが長期SMAを上抜けたら買い：",
          "",
          "```python",
          "# 短期(5日)と長期(20日)のSMA",
          'df["SMA5"] = df["Close"].rolling(5).mean()',
          'df["SMA20"] = df["Close"].rolling(20).mean()',
          "",
          "# クロス判定",
          'if df["SMA5"].iloc[-1] > df["SMA20"].iloc[-1]:',
          '    if df["SMA5"].iloc[-2] <= df["SMA20"].iloc[-2]:',
          '        bt.buy(tag="golden_cross")',
          "```",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "RISK_001",
    description: "ストップロス設定後、リスク管理のヒント",
    cells: [
      {
        name: "_hint_risk_management",
        code: [
          '"""',
          "リスク管理の基本",
          '"""',
          "mo.md('''",
          "## リスク管理の基本",
          "",
          "### ストップロス(SL)とテイクプロフィット(TP)",
          "",
          "```python",
          "# 買い注文時にSL/TPを設定",
          "bt.buy(",
          "    sl=2400,  # この価格以下で自動損切り",
          "    tp=2700,  # この価格以上で自動利確",
          '    tag="managed_trade"',
          ")",
          "```",
          "",
          "### リスクリワード比",
          "",
          "推奨: 1:2以上（リスク1に対してリワード2）",
          "",
          "例: SL幅100円なら、TP幅は200円以上",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },

  // ========================================
  // 追加テンプレート（Phase 4B）
  // ========================================
  {
    skillId: "SANDBOX_003",
    description: "買値確認のヒント",
    cells: [
      {
        name: "_hint_entry_price",
        code: [
          '"""',
          "買値を確認する方法",
          '"""',
          "mo.md('''",
          "## 買値を確認しよう",
          "",
          "買い注文を出したら、いくらで買えたか確認しましょう。",
          "",
          "```python",
          "# 保有中の取引を確認",
          "for trade in bt.trades:",
          '    print(f"銘柄: {trade.code}")',
          '    print(f"買値: {trade.entry_price:,.0f}円")',
          '    print(f"株数: {trade.size}株")',
          "```",
          "",
          "### ポイント",
          "",
          "- `trade.entry_price` が買った時の価格",
          "- `trade.size` が保有株数",
          "- この情報は売却タイミングを決めるのに重要！",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "SANDBOX_005",
    description: "チャート振り返りガイド",
    cells: [
      {
        name: "_hint_chart_review",
        code: [
          '"""',
          "チャートで売買を振り返る",
          '"""',
          "mo.md('''",
          "## チャートで振り返る",
          "",
          "上のチャートを見てください。",
          "",
          "### 売買マーカーの読み方",
          "",
          "- **緑の▲**: 買いポイント（エントリー）",
          "- **赤の▼**: 売りポイント（決済）",
          "",
          "### 振り返りのポイント",
          "",
          "1. 買ったタイミングは適切だったか？",
          "2. 売ったタイミングはどうだったか？",
          "3. もっと良いタイミングはあったか？",
          "",
          "> 振り返りは上達の第一歩です！",
          "''')",
        ].join("\n"),
        afterCell: "_hint_review_chart",
      },
    ],
  },
  {
    skillId: "FAIL_001",
    description: "含み損は授業料（教育）",
    cells: [
      {
        name: "_lesson_unrealized_loss",
        code: [
          '"""',
          "含み損を経験した時の心構え",
          '"""',
          "mo.md('''",
          "## 含み損は「勉強代」",
          "",
          "買った株が値下がりすることは珍しくありません。",
          "これは失敗ではなく、投資の現実を学ぶ第一歩です。",
          "",
          "```python",
          "# 含み損益を確認",
          "for trade in bt.trades:",
          "    if trade.pl < 0:",
          '        print(f"含み損: {trade.pl:,.0f}円 ({trade.pl_pct:.1f}%)")',
          "```",
          "",
          "### プロの考え方",
          "",
          "- 100%勝てる投資家は存在しない",
          "- 重要なのは「トータルでプラス」になること",
          "- 小さな損失を受け入れ、大きな利益を狙う",
          "",
          "> 「損小利大」がプロの鉄則",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "FAIL_002",
    description: "損切りはプロの証（教育）",
    cells: [
      {
        name: "_lesson_stop_loss",
        code: [
          '"""',
          "損切りの重要性を学ぶ",
          '"""',
          "mo.md('''",
          "## 損切りはプロの証",
          "",
          "損切り（ロスカット）は、損失を最小限に抑えるための重要な技術です。",
          "",
          "```python",
          "# 損切りの実行",
          "for trade in bt.trades:",
          "    if trade.pl < 0 and trade.pl_pct < -5:  # 5%以上の損失",
          "        trade.close()",
          '        print("損切り完了 - これ以上の損失を防いだ！")',
          "```",
          "",
          "### なぜ損切りが重要？",
          "",
          "| 含み損 | 回復に必要な利益率 |",
          "|--------|-------------------|",
          "| -10% | +11.1% |",
          "| -20% | +25.0% |",
          "| -50% | +100.0% |",
          "| -90% | +900.0% |",
          "",
          "損失が大きくなるほど、回復が困難になります。",
          "**早めの損切りが資金を守る！**",
          "''')",
        ].join("\n"),
        afterCell: "_lesson_unrealized_loss",
      },
    ],
  },
  {
    skillId: "DATA_001",
    description: "get_stock_daily使い方",
    cells: [
      {
        name: "_hint_get_stock_daily",
        code: [
          '"""',
          "株価データの取得方法",
          '"""',
          "mo.md('''",
          "## get_stock_daily() の使い方",
          "",
          "`get_stock_daily(code)` で株価データを取得できます。",
          "",
          "```python",
          "# トヨタの株価データを取得",
          'df = get_stock_daily("7203")',
          "",
          "# 中身を確認",
          "print(df.head())",
          "print(df.columns)  # Open, High, Low, Close, Volume",
          "```",
          "",
          "### 主要な銘柄コード",
          "",
          "| 銘柄 | コード |",
          "|------|--------|",
          "| トヨタ | 7203 |",
          "| ソニー | 6758 |",
          "| 日立 | 6501 |",
          "| 任天堂 | 7974 |",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "SET_001",
    description: "set_data使い方",
    cells: [
      {
        name: "_hint_set_data",
        code: [
          '"""',
          "データをBacktestにセットする方法",
          '"""',
          "mo.md('''",
          "## set_data() の使い方",
          "",
          "取得したデータをBacktestにセットします。",
          "",
          "```python",
          "# 1. データを取得",
          'code = "7203"',
          "df = get_stock_daily(code)",
          "",
          "# 2. Backtestにセット",
          "bt.set_data({code: df})",
          "",
          "# 3. これで取引可能！",
          "bt.buy()  # ← これが動くようになる",
          "```",
          "",
          "### 複数銘柄をセットする場合",
          "",
          "```python",
          "bt.set_data({",
          '    "7203": df_toyota,',
          '    "6758": df_sony,',
          "})",
          "```",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "TRADE_001",
    description: "フルモードでの初取引",
    cells: [
      {
        name: "_hint_first_trade_full",
        code: [
          '"""',
          "フルモードでの取引の流れ",
          '"""',
          "mo.md('''",
          "## フルモードで株を買う",
          "",
          "自分でセットアップしたBacktestで取引してみましょう。",
          "",
          "```python",
          "# 基本の買い注文",
          "bt.buy()  # 現在の銘柄を全力で買う",
          "",
          "# サイズを指定",
          "bt.buy(size=100)  # 100株だけ買う",
          "",
          "# タグを付ける（後で分析しやすい）",
          'bt.buy(tag="entry_signal")',
          "```",
          "",
          "### 次のステップ",
          "",
          "1. ポジションを確認 → `bt.position`",
          "2. 時間を進める → `bt.step()`",
          "3. 決済する → `trade.close()`",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "IND_003",
    description: "ゴールデンクロス検出",
    cells: [
      {
        name: "_hint_golden_cross",
        code: [
          '"""',
          "ゴールデンクロスの検出方法",
          '"""',
          "mo.md('''",
          "## ゴールデンクロス戦略",
          "",
          "短期移動平均線が長期移動平均線を**下から上に**抜けた時が買いシグナル。",
          "",
          "```python",
          "# 移動平均線を計算",
          'df["SMA5"] = df["Close"].rolling(5).mean()',
          'df["SMA20"] = df["Close"].rolling(20).mean()',
          "",
          "# 現在と前日の値を取得",
          'sma5_now = df["SMA5"].iloc[-1]',
          'sma20_now = df["SMA20"].iloc[-1]',
          'sma5_prev = df["SMA5"].iloc[-2]',
          'sma20_prev = df["SMA20"].iloc[-2]',
          "",
          "# ゴールデンクロス判定",
          "if sma5_prev <= sma20_prev and sma5_now > sma20_now:",
          '    print("ゴールデンクロス発生！")',
          '    bt.buy(tag="golden_cross")',
          "```",
          "",
          "### 注意点",
          "",
          "- 遅延シグナルなので、エントリーが遅れることがある",
          "- 他の指標と組み合わせると精度向上",
          "''')",
        ].join("\n"),
        afterCell: "_hint_sma_usage",
      },
    ],
  },
  {
    skillId: "IND_005",
    description: "RSI計算方法",
    cells: [
      {
        name: "_hint_rsi",
        code: [
          '"""',
          "RSI（相対力指数）の計算と活用",
          '"""',
          "mo.md('''",
          "## RSI（相対力指数）",
          "",
          "RSIは0〜100の範囲で、買われすぎ/売られすぎを判断します。",
          "",
          "```python",
          "# RSIを計算する関数",
          "def calc_rsi(series, period=14):",
          "    delta = series.diff()",
          "    gain = delta.where(delta > 0, 0)",
          "    loss = -delta.where(delta < 0, 0)",
          "    avg_gain = gain.rolling(period).mean()",
          "    avg_loss = loss.rolling(period).mean()",
          "    rs = avg_gain / avg_loss",
          "    return 100 - (100 / (1 + rs))",
          "",
          "# RSIを計算",
          'df["RSI"] = calc_rsi(df["Close"])',
          "```",
          "",
          "### RSIの読み方",
          "",
          "| RSI値 | 状態 | アクション |",
          "|-------|------|-----------|",
          "| > 70 | 買われすぎ | 売り検討 |",
          "| < 30 | 売られすぎ | 買い検討 |",
          "| 30-70 | 中立 | 様子見 |",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "RISK_003",
    description: "SL/TP併用のヒント",
    cells: [
      {
        name: "_hint_sl_tp_combo",
        code: [
          '"""',
          "SLとTPを併用したリスク管理",
          '"""',
          "mo.md('''",
          "## SL/TP併用のプロテクニック",
          "",
          "ストップロスとテイクプロフィットを同時に設定して、リスクを管理します。",
          "",
          "```python",
          "# 現在価格を取得",
          'current_price = df["Close"].iloc[-1]',
          "",
          "# リスクリワード 1:2 で設定",
          "sl_pct = 0.03  # 3%の損失で損切り",
          "tp_pct = 0.06  # 6%の利益で利確",
          "",
          "bt.buy(",
          "    sl=current_price * (1 - sl_pct),",
          "    tp=current_price * (1 + tp_pct),",
          '    tag="rr_1to2"',
          ")",
          "```",
          "",
          "### 推奨リスクリワード比",
          "",
          "| 比率 | 必要勝率 | 評価 |",
          "|------|---------|------|",
          "| 1:1 | 50%以上 | 最低限 |",
          "| 1:2 | 33%以上 | 推奨 |",
          "| 1:3 | 25%以上 | 優良 |",
          "",
          "> 高いリスクリワード比なら、勝率が低くても利益が出る！",
          "''')",
        ].join("\n"),
        afterCell: "_hint_risk_management",
      },
    ],
  },

  // ========================================
  // Phase D: 追加テンプレート（教育的ヒント）
  // ========================================
  {
    skillId: "SETUP_002",
    description: "BackcastPro のインポート方法",
    cells: [
      {
        name: "_hint_import_backcastpro",
        code: [
          '"""',
          "BackcastPro のインポート方法",
          '"""',
          "mo.md('''",
          "## BackcastPro をインポートする",
          "",
          "フルモードでは、自分でライブラリをインポートします。",
          "",
          "```python",
          "from BackcastPro import Backtest, get_stock_daily",
          "```",
          "",
          "### 主要なクラスと関数",
          "",
          "| 名前 | 用途 |",
          "|------|------|",
          "| `Backtest` | バックテストエンジン本体 |",
          "| `get_stock_daily` | 株価データの取得 |",
          "",
          "これが全ての出発点です！",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "SETUP_003",
    description: "Backtest 初期化パラメータ解説",
    cells: [
      {
        name: "_hint_backtest_init",
        code: [
          '"""',
          "Backtest 初期化のパラメータ解説",
          '"""',
          "mo.md('''",
          "## Backtest の初期化",
          "",
          "```python",
          "bt = Backtest(",
          "    cash=1_000_000,      # 初期資金（円）",
          "    commission=0.001,    # 手数料率（0.1%）",
          "    finalize_trades=True # 取引を自動確定",
          ")",
          "```",
          "",
          "### パラメータ詳細",
          "",
          "| パラメータ | 型 | 説明 |",
          "|-----------|-----|------|",
          "| `cash` | int | 初期資金。多いほど大きなポジションが取れる |",
          "| `commission` | float | 売買手数料率。0.001 = 0.1% |",
          "| `finalize_trades` | bool | True で sell 時に即決済 |",
          "",
          "> 初期資金は戦略のリスク許容度に合わせて設定しましょう",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "IND_002",
    description: "SMA を DataFrame に追加する方法",
    cells: [
      {
        name: "_hint_sma_column",
        code: [
          '"""',
          "SMA を DataFrame に列として追加する",
          '"""',
          "mo.md('''",
          "## SMA を DataFrame に追加する",
          "",
          "計算した移動平均線をデータに組み込みましょう。",
          "",
          "```python",
          "# 終値の5日移動平均",
          'df["SMA5"] = df["Close"].rolling(5).mean()',
          "",
          "# 20日移動平均",
          'df["SMA20"] = df["Close"].rolling(20).mean()',
          "",
          "# 確認",
          'print(df[["Close", "SMA5", "SMA20"]].tail())',
          "```",
          "",
          "### ポイント",
          "",
          "- `rolling(N)` で N 日間のウィンドウを作成",
          "- `.mean()` で平均を計算",
          "- 最初の N-1 行は `NaN` になる（データ不足）",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "IND_004",
    description: "デッドクロス検出",
    cells: [
      {
        name: "_hint_dead_cross",
        code: [
          '"""',
          "デッドクロスの検出方法",
          '"""',
          "mo.md('''",
          "## デッドクロス戦略",
          "",
          "短期移動平均線が長期移動平均線を**上から下に**抜けた時が売りシグナル。",
          "",
          "```python",
          "# 移動平均線を計算",
          'df["SMA5"] = df["Close"].rolling(5).mean()',
          'df["SMA20"] = df["Close"].rolling(20).mean()',
          "",
          "# 現在と前日の値を取得",
          'sma5_now = df["SMA5"].iloc[-1]',
          'sma20_now = df["SMA20"].iloc[-1]',
          'sma5_prev = df["SMA5"].iloc[-2]',
          'sma20_prev = df["SMA20"].iloc[-2]',
          "",
          "# デッドクロス判定",
          "if sma5_prev >= sma20_prev and sma5_now < sma20_now:",
          '    print("デッドクロス発生！")',
          "    for trade in bt.trades:",
          '        trade.close(tag="dead_cross")',
          "```",
          "",
          "### ゴールデンクロスとの組み合わせ",
          "",
          "- **ゴールデンクロス** → 買いシグナル",
          "- **デッドクロス** → 売りシグナル",
          "- セットで使うと売買タイミングが明確に！",
          "''')",
        ].join("\n"),
        afterCell: "_hint_golden_cross",
      },
    ],
  },
  {
    skillId: "IND_007",
    description: "ボリンジャーバンド計算",
    cells: [
      {
        name: "_hint_bollinger",
        code: [
          '"""',
          "ボリンジャーバンドの計算",
          '"""',
          "mo.md('''",
          "## ボリンジャーバンド",
          "",
          "移動平均線を中心に、標準偏差で上下のバンドを描きます。",
          "",
          "```python",
          "period = 20",
          'df["BB_mid"] = df["Close"].rolling(period).mean()',
          'df["BB_std"] = df["Close"].rolling(period).std()',
          'df["BB_upper"] = df["BB_mid"] + 2 * df["BB_std"]',
          'df["BB_lower"] = df["BB_mid"] - 2 * df["BB_std"]',
          "```",
          "",
          "### 読み方",
          "",
          "| 状態 | 意味 |",
          "|------|------|",
          "| 価格 > 上バンド | 買われすぎ（売り検討） |",
          "| 価格 < 下バンド | 売られすぎ（買い検討） |",
          "| バンド幅が狭い | ブレイクアウトの前兆 |",
          "",
          "> 約95%の値動きが±2σの範囲内に収まります",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "IND_009",
    description: "MACD 計算",
    cells: [
      {
        name: "_hint_macd",
        code: [
          '"""',
          "MACD（移動平均収束拡散法）の計算",
          '"""',
          "mo.md('''",
          "## MACD（Moving Average Convergence Divergence）",
          "",
          "トレンドの方向と強さを判断する指標です。",
          "",
          "```python",
          "# EMA（指数移動平均）を計算",
          'ema12 = df["Close"].ewm(span=12).mean()',
          'ema26 = df["Close"].ewm(span=26).mean()',
          "",
          "# MACD = 短期EMA - 長期EMA",
          'df["MACD"] = ema12 - ema26',
          "",
          "# シグナル線 = MACDの9日EMA",
          'df["Signal"] = df["MACD"].ewm(span=9).mean()',
          "",
          "# ヒストグラム = MACD - シグナル",
          'df["Hist"] = df["MACD"] - df["Signal"]',
          "```",
          "",
          "### 売買シグナル",
          "",
          "- **MACD > シグナル** → 買いシグナル",
          "- **MACD < シグナル** → 売りシグナル",
          "- **ヒストグラム** が正→負 or 負→正 の転換点に注目",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "TRADE_008",
    description: "戦略関数の作成方法",
    cells: [
      {
        name: "_hint_strategy_function",
        code: [
          '"""',
          "戦略関数の作成方法",
          '"""',
          "mo.md('''",
          "## 戦略関数を作る",
          "",
          "売買ロジックを関数にまとめると、再利用しやすくなります。",
          "",
          "```python",
          "def my_strategy(bt):",
          '    """シンプルなSMAクロス戦略"""',
          '    df = bt._data[bt._current_code]',
          '    sma5 = df["Close"].rolling(5).mean()',
          '    sma20 = df["Close"].rolling(20).mean()',
          "",
          "    # ゴールデンクロスで買い",
          "    if sma5.iloc[-2] <= sma20.iloc[-2] and sma5.iloc[-1] > sma20.iloc[-1]:",
          "        if not bt.trades:",
          '            bt.buy(tag="golden_cross")',
          "",
          "    # デッドクロスで売り",
          "    if sma5.iloc[-2] >= sma20.iloc[-2] and sma5.iloc[-1] < sma20.iloc[-1]:",
          "        for trade in bt.trades:",
          '            trade.close(tag="dead_cross")',
          "```",
          "",
          "### 使い方",
          "",
          "```python",
          "# 毎ステップで戦略を実行",
          "my_strategy(bt)",
          "bt.step()",
          "```",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "TRADE_010",
    description: "run() ループ実行の解説",
    cells: [
      {
        name: "_hint_run_loop",
        code: [
          '"""',
          "run() によるループ実行",
          '"""',
          "mo.md('''",
          "## run() でバックテストを一括実行",
          "",
          "`step()` を1日ずつ呼ぶ代わりに、`run()` で全期間を一括実行できます。",
          "",
          "```python",
          "def my_strategy(bt):",
          '    # ... 戦略ロジック ...',
          "    pass",
          "",
          "# 全期間を一括実行",
          "bt.run(my_strategy)",
          "```",
          "",
          "### step() vs run()",
          "",
          "| | step() | run() |",
          "|---|--------|-------|",
          "| 実行 | 1日ずつ手動 | 全期間を自動 |",
          "| 用途 | 学習・デバッグ | 本番バックテスト |",
          "| 速度 | 遅い | 速い |",
          "",
          "> 戦略が完成したら `run()` で本番テストしましょう！",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
  {
    skillId: "RISK_002",
    description: "テイクプロフィット設定",
    cells: [
      {
        name: "_hint_take_profit",
        code: [
          '"""',
          "テイクプロフィット（利確）の設定",
          '"""',
          "mo.md('''",
          "## テイクプロフィット（TP）",
          "",
          "目標価格に達したら自動的に利益確定します。",
          "",
          "```python",
          "# 現在価格の5%上で利確",
          'current_price = df["Close"].iloc[-1]',
          "bt.buy(tp=current_price * 1.05)",
          "",
          "# SL と TP を同時に設定",
          "bt.buy(",
          "    sl=current_price * 0.97,  # 3%下で損切り",
          "    tp=current_price * 1.06,  # 6%上で利確",
          ")",
          "```",
          "",
          "### なぜ TP が重要？",
          "",
          "- 欲張りすぎて利益を逃すのを防ぐ",
          "- 感情に左右されない機械的な決済",
          "- SL と組み合わせてリスクリワード比を管理",
          "",
          "> 「頭と尻尾はくれてやれ」- 利益の最大化より確実な利確を",
          "''')",
        ].join("\n"),
        afterCell: "_hint_risk_management",
      },
    ],
  },
  {
    skillId: "CHART_003",
    description: "インジケーターをチャートに表示",
    cells: [
      {
        name: "_hint_chart_indicators",
        code: [
          '"""',
          "インジケーターをチャートに表示する",
          '"""',
          "mo.md('''",
          "## チャートにインジケーターを重ねる",
          "",
          "計算したインジケーターをチャートに表示できます。",
          "",
          "```python",
          "# SMA を計算して DataFrame に追加",
          'df["SMA5"] = df["Close"].rolling(5).mean()',
          'df["SMA20"] = df["Close"].rolling(20).mean()',
          "",
          "# データを更新してチャート表示",
          "bt.set_data({code: df})",
          "",
          "# backtest_chart は追加列を自動検出",
          "from chart import backtest_chart",
          "backtest_chart(bt, code=code)",
          "```",
          "",
          "### 表示可能なインジケーター",
          "",
          "DataFrame に列を追加するだけで自動的に表示されます：",
          "- SMA / EMA（移動平均線）",
          "- ボリンジャーバンド",
          "- その他カスタム列",
          "''')",
        ].join("\n"),
        afterCell: "_playground",
      },
    ],
  },
];

/**
 * スキルIDから注入テンプレートを取得
 */
export function getInjectionTemplate(
  skillId: string
): InjectionTemplate | undefined {
  return injectionTemplates.find((t) => t.skillId === skillId);
}

/**
 * 注入が必要なスキルIDのリスト
 */
export function getInjectableSkillIds(): string[] {
  return injectionTemplates.map((t) => t.skillId);
}
