/* Copyright 2026 Marimo. All rights reserved. */

import { beforeEach, describe, expect, it } from "vitest";
import type { CellId } from "@/core/cells/ids";
import { store } from "@/core/state/jotai";
import {
  addCellToGridLayout,
  isCellInGrid,
  layoutStateAtom,
} from "../layout";

const createCellId = (id: string): CellId => id as CellId;

describe("addCellToGridLayout", () => {
  beforeEach(() => {
    // Reset layout state before each test with grid mode and undefined gridLayout
    store.set(layoutStateAtom, {
      selectedLayout: "grid",
      layoutData: {}, // gridLayout is undefined
      autoLayoutEnabled: true,
      layoutWasAutoGenerated: false,
    });
  });

  it("should initialize grid layout when layoutData.grid is undefined", () => {
    const cellId = createCellId("test-cell-id");

    // Initially, cell should not be in grid
    expect(isCellInGrid(cellId)).toBe(false);

    // Call addCellToGridLayout with undefined gridLayout
    addCellToGridLayout(cellId);

    // Grid layout should now be initialized and cell should be in grid
    const state = store.get(layoutStateAtom);
    expect(state.layoutData.grid).toBeDefined();
    expect(state.layoutData.grid?.cells.length).toBe(1);
    expect(isCellInGrid(cellId)).toBe(true);
  });

  it("should add cell to existing grid layout", () => {
    const cellId1 = createCellId("cell-1");
    const cellId2 = createCellId("cell-2");

    addCellToGridLayout(cellId1);
    addCellToGridLayout(cellId2);

    const state = store.get(layoutStateAtom);
    expect(state.layoutData.grid?.cells.length).toBe(2);
    expect(isCellInGrid(cellId1)).toBe(true);
    expect(isCellInGrid(cellId2)).toBe(true);
  });

  it("should not add duplicate cell", () => {
    const cellId = createCellId("test-cell-id");

    addCellToGridLayout(cellId);
    addCellToGridLayout(cellId); // Duplicate add

    const state = store.get(layoutStateAtom);
    expect(state.layoutData.grid?.cells.length).toBe(1);
  });

  it("should not add cell when selectedLayout is not grid", () => {
    const cellId = createCellId("test-cell-id");

    // Set layout to vertical
    store.set(layoutStateAtom, {
      selectedLayout: "vertical",
      layoutData: {},
      autoLayoutEnabled: true,
      layoutWasAutoGenerated: false,
    });

    addCellToGridLayout(cellId);

    const state = store.get(layoutStateAtom);
    expect(state.layoutData.grid).toBeUndefined();
    expect(isCellInGrid(cellId)).toBe(false);
  });

  it("should place cells with correct positions", () => {
    const cellId1 = createCellId("cell-1");
    const cellId2 = createCellId("cell-2");

    addCellToGridLayout(cellId1);
    addCellToGridLayout(cellId2);

    const state = store.get(layoutStateAtom);
    const cells = state.layoutData.grid?.cells;

    // First cell should be at top (y=0)
    expect(cells?.[0]?.y).toBe(0);
    // Second cell should be below the first
    expect(cells?.[1]?.y).toBeGreaterThan(0);
  });
});

describe("isCellInGrid", () => {
  beforeEach(() => {
    store.set(layoutStateAtom, {
      selectedLayout: "grid",
      layoutData: {},
      autoLayoutEnabled: true,
      layoutWasAutoGenerated: false,
    });
  });

  it("should return false when grid layout is undefined", () => {
    const cellId = createCellId("test-cell-id");
    expect(isCellInGrid(cellId)).toBe(false);
  });

  it("should return false when selectedLayout is not grid", () => {
    const cellId = createCellId("test-cell-id");

    store.set(layoutStateAtom, {
      selectedLayout: "vertical",
      layoutData: {},
      autoLayoutEnabled: true,
      layoutWasAutoGenerated: false,
    });

    expect(isCellInGrid(cellId)).toBe(false);
  });

  it("should return true when cell is in grid", () => {
    const cellId = createCellId("test-cell-id");

    addCellToGridLayout(cellId);

    expect(isCellInGrid(cellId)).toBe(true);
  });

  it("should return false when cell is not in grid", () => {
    const cellId1 = createCellId("cell-1");
    const cellId2 = createCellId("cell-2");

    addCellToGridLayout(cellId1);

    expect(isCellInGrid(cellId1)).toBe(true);
    expect(isCellInGrid(cellId2)).toBe(false);
  });
});
